# Dockerfile para Backend Node.js (Express + Prisma)

FROM node:20-alpine

WORKDIR /app

# Instala dependências do Node.js
COPY package*.json ./
RUN npm install --production=false

# Copia código e Prisma
COPY prisma ./prisma
RUN npx prisma generate
COPY . .

# Build do projeto
RUN npm run build

EXPOSE 5432

CMD ["node", "dist/server.js"]
